import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '@/copmonent/super-admin/header'
import Sidebar from '@/copmonent/super-admin/sidebar'
import Footer from '@/copmonent/super-admin/footer'
import Rightsidbar from '@/copmonent/super-admin/right-sidebar'
import Skin from '@/copmonent/super-admin/skin'


// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="container-scroller">
                    <Header />
                    <div className="container-fluid page-body-wrapper">
                        <Skin />
                        <Rightsidbar />
                        <Sidebar />
                        <div className="main-panel">
                            <div className="content-wrapper">
                                <div className="row">
                                    <div className="col-md-12 grid-margin">
                                        <div className="row">
                                            <div className="col-12 col-xl-8 mb-4 mb-xl-0">
                                                <h3 className="font-weight-bold">Welcome Aamir</h3>
                                                <h6 className="font-weight-normal mb-0">All systems are running smoothly! You have <span className="text-primary">3 unread alerts!</span></h6>
                                            </div>
                                            <div className="col-12 col-xl-4">
                                                <div className="justify-content-end d-flex">
                                                    <div className="dropdown flex-md-grow-1 flex-xl-grow-0">
                                                        <button className="btn btn-sm btn-light bg-white dropdown-toggle" type="button" id="dropdownMenuDate2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                                            <i className="mdi mdi-calendar"></i> Today (10 Jan 2021)
                                                        </button>
                                                        <div className="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuDate2">
                                                            <a className="dropdown-item" href="#">January - March</a>
                                                            <a className="dropdown-item" href="#">March - June</a>
                                                            <a className="dropdown-item" href="#">June - August</a>
                                                            <a className="dropdown-item" href="#">August - November</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <Footer />


                        </div>
                    </div>
                </div>

            </main>
        </>
    )
}